language: java

sudo: false

# Triggers an update of the OracleJDK distribution. Travis is currently running v8u31 which
# exposes problems with the instrumentation of invokedynamic call sites.
addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
  only:
    - master

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=-Pjava8
    - jdk: oraclejdk7
      env: TARGET=-Pjava7

script: mvn jacoco:prepare-agent verify jacoco:report $TARGET -Pintegration -Dnet.bytebuddy.test.travis=true

after_success:
  - mvn coveralls:report
